#' SiteAbbrev
#'
#' Make site abbreviation table
#'
#' @param scan_fb a data frame; cleaned SCAN data
#' @param out_path a string; path to save figure
#'
#' @return site_table; a data frame with site name abbreviations
#'
#' @importFrom magrittr %>%
#'
#' @export

SiteAbbrev <- function(scan_fb, out_path = 'checkpoints/csv') {
  sites <- unique(scan_fb$site) %>%
    sort()

  abbrev <- c('Boege Alvarado (Fremont)',
              'Boege Alvarado (Newark)',
              'Boege Alvarado (Union City)',
              'Akron',
              'Altamonte Springs',
              'Aquia',
              'Archie Elledge',
              'Bayshore',
              'Big Creek',
              'Brunswick',
              'Cahaba River',
              'Calera Creek',
              'Camp Creek',
              'Capital Region',
              'Central Contra Costa',
              'Central Marin',
              'Central Marin (W Railroad)',
              'Central Valley',
              'Ann Arbor',
              'Bangor',
              'Carmel',
              'Clinton',
              "Coeur d'Alene",
              'Davis',
              'Dover',
              'Essex',
              'Gainesville',
              'Garland Rowlett Creek',
              'Harrison',
              'Hollister',
              'Madera',
              'Mankato',
              'Markshalltown',
              'Paso Robles',
              'Rochester',
              'San Leandro',
              'San Mateo & Estero',
              'Santa Cruz (City)',
              'Santa Cruz (County)',
              'Santa Rosa',
              'South Bend',
              'Sunnyvale',
              'Warren',
              'Wheeling',
              'Yankton',
              'Youngstown',
              'Clark County',
              'Coastal',
              'CODIGA',
              'Coralville',
              'Cumberland',
              'Deer Island',
              'DELCORA',
              'Dillman Road',
              'Duck Creek',
              'E.W. Blom Point Loma',
              'East Bay',
              'Eastern',
              'Ellis Creek',
              'Esparto',
              'Fairfield-Suisun',
              'Five Mile Creek',
              'Glenbard',
              'Grandville',
              'Hagerstown',
              'Hall Street',
              'Hamlin',
              'Hollywood Road',
              'Hyperion',
              'Jackson',
              'JB Latham',
              'Jeffersonville',
              'John M. Asplund',
              'Johnnie Mosley',
              'Johns Creek',
              'Joint',
              'Kansas City',
              'Lancaster',
              'Lander Street',
              'Las Gallinas',
              'Lawrence Kansas',
              'Little Falls Run',
              'Little River',
              'Lompoc',
              'Los Banos',
              'Loxahatchee',
              'Marlay Taylor',
              'MDWASD Central',
              'MDWASD North',
              'MDWASD South',
              'Merced',
              "Modesto's Sutter",
              'Monterey One',
              'Monteplier',
              'Morris Forman',
              'Mt. Pleasant',
              'Kaw Point',
              'Muscatine',
              'North Water',
              'Norhtwest Water',
              'Novato',
              'Oceanside',
              'Ottumwa',
              'Palo Alto',
              'Parker North',
              'Parker South',
              'Passaic Valley',
              'Penacook',
              'Portland',
              'Provo City',
              'Red Wing',
              'Regional',
              'Regional No. 1',
              'River Road',
              'Riverside',
              'RM Clayton',
              'Sacramento',
              'Salina',
              'San Jose-Santa Clara',
              'Sausalito-Marin',
              'Seaford',
              'Mid-Coastside',
              'Southern Marin',
              'Silicon Valley',
              'SJRA No. 1',
              'SJRA No. 2',
              'SJRA No. 3',
              'Soscol',
              'South Bay',
              'South Burlington',
              'South Columbus',
              'South County',
              'South Laredo',
              'South Monmouth',
              'South River',
              'South Water',
              'San Francisco',
              'St. Cloud',
              'Somerset Raritan',
              'Hillsville',
              'Ocean',
              'Traverse City',
              'Turkey Creek',
              'Turlock',
              'Upper Blackstone',
              'Utoy Creek',
              'Vallejo',
              'Valley Creek',
              'Valley',
              'Village Creek',
              'West Boise',
              'West County',
              'Weaton',
              'Wichita Falls',
              'Windsor',
              'Winters',
              'Wolcott',
              'Woodland',
              'York',
              'Zacate Creek')

  site_table <- cbind(sites, abbrev) %>%
    data.frame() %>%
    magrittr::set_colnames(c('site name', 'abbreviation'))

  write.csv(site_table,
            file      = file.path(out_path, 'site_abbrev.csv'),
            row.names = FALSE)

  return (site_table)
}
